server:
  port: 80
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sd0915
  session:
    store-type: none

security:
  basic:
    enabled: true
  user:
    password: sd0915
sdg:
  security:
    browser:
      ignoreUrls:
        - /demo-signin.html
        - /demo-signUp.html
        - /**/swagger**/**
        - /qqLogin/callback.do
      loginPage: /demo-signin.html
      signUpUrl: /demo-signUp.html
    code:
      image:
        width: 90
        height: 35
        size: 30
        length: 4
        expireIn: 120
        url:
          - /auth/form
      sms:
        length: 6
        expireIn: 240
        url:
          - /auth/mobile
    social:
      filterProcessesUrl: /qqLogin
      qq:
        appId: 101386962
        appSecret: 2a0f820407df400b84a854d054be8b6a
        providerId: callback.do